### ISSUE TITLE
Support for Material Darker

### ISSUE THREAD

**Issue by iKenshu** [hlrossato/material-monokai#1]
I think should be nice to add this support, because this is only for the blue one right? Sorry if I'm wrong.

**Comment by hlrossato** [comment]
Hi @iKenshu I've been very busy but I'll try to implement the other colours too and yes, you're right. This version is just for the blue one. Thanks.

**Comment by hlrossato** [comment]
Hi @iKenshu, I've just updated the theme. Now you'd be able to choose between the colors. Please let me know if you find some bugs or anything else. Thanks.

**Comment by iKenshu** [comment]
Hey @hlrossato 

I tried this and its perfect! Thank you very much! 👏
