### ISSUE TITLE
material-monokai breaks new Material Theme version

### ISSUE THREAD

**Issue by RichRat** [hlrossato/material-monokai#2]
Hi,

since this Monday (23.10.17) the Material Theme looks like this
![brokenmaterial](https://user-images.githubusercontent.com/6141834/31933486-87238dae-b8a9-11e7-9a54-ae45755a9ed6.png)
when i have selected the material-monokai Colorscheme.
This persists when restarting sublime. The only way i've found to fix the sublime ui is to select another theme and activate the material theme again.

Regards,
Rich

**Comment by hlrossato** [comment]
Is it still broken? I've been very busy at the moment but will try to fix asap. Mine is just working fine. Just confirm, please @RichRat . Thanks

**Comment by RichRat** [comment]
I'll recheck tomorrow.

**Comment by RichRat** [comment]
I checked with a clean sublime install and couldn't reproduce the problem. So this was probably a side effect of something.

**Comment by hlrossato** [comment]
Thanks @RichRat
