### ISSUE TITLE
Breaking Markdown highlighting

### ISSUE THREAD

**Issue by Moonire** [hlrossato/material-monokai#3]
I noticed that material-monokai did't automatically support markdown text highlighting. It displays it as plain text where as other material themes kept the highlighting working. Is there any way around this problem ?

**Comment by hlrossato** [comment]
@Moonire are you referring to the Monokai Extended syntax?

**Comment by Moonire** [comment]
I'm not sure, I have installed the Material Monokai package and this is the color scheme found in the settings if it helps:
"color_scheme": "Packages/Material Monokai/MaterialMonokaiDark.tmTheme",

**Comment by Moonire** [comment]
Ok I just installed the Monokai Extended and it solved the problem !
Thanks
